[package]
name = "deeps-pallets-api"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
anyhow = "1.0"
sp-core = { git = "https://github.com/deepslabs/polkadot-sdk", branch = "deep-stable2603" }
sp-runtime = { git = "https://github.com/deepslabs/polkadot-sdk", branch = "deep-stable2603" }
frame-system = { git = "https://github.com/deepslabs/polkadot-sdk", branch = "deep-stable2603" }
precompile-utils = { git = "https://github.com/deepslabs/frontier.git", branch = "deep-stable2603" }
subxt = { git = "https://github.com/deepslabs/subxt.git", branch = "deep-stable2603" }
deeps-telemetry-client = { git = "https://github.com/deepslabs/deeps-telemetry-client", branch = "main", optional = true }
codec = { package = "parity-scale-codec", version = "3.7.5", features = ["derive", "full"] }
tokio = { version = "1.27.0", features = ["macros"] }
url = { version = "^2.2", features = ["serde"] }
hex = "0.4.2"
serde = { version = "1.0.195", default-features = false, features = ["alloc", "derive"] }
libsecp256k1 = { version = "0.3.2", default-features = false }


# local dependencies
node-primitives = { package = "deeps-node-primitives", git = "https://github.com/deepslabs/deeps-common", branch = "deep-stable2603" }
chain-bridge = { package = "deeps-chain-bridge", git = "https://github.com/deepslabs/deeps-common", branch = "deep-stable2603" }

# extra dependencies
ethereum = { version = "0.18.2", features = ["with-scale"] }

[dev-dependencies]
env_logger = "0.9"

[features]
telemetry = ["deeps-telemetry-client"]